[package]
name = "declipt"
version = "0.1.0"
edition = "2021"

[dependencies]
minhook = "0.6.0"
libloading = "0.8.5"
winapi = { version = "0.3.9", features = ["winnt", "memoryapi", "errhandlingapi"] }
pdb = "0.8.0"

colored = "2"
thiserror = "1"
anyhow = "1"
